# Generated by Django 5.2.8 on 2025-11-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
    ]
